# Generated by Django 2.2 on 2019-04-30 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
        migrations.RemoveField(
            model_name='list',
            name='position',
        ),
    ]
