# Generated by Django 2.2 on 2019-04-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
        migrations.AlterField(
            model_name='list',
            name='position',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
