# Generated by Django 2.2 on 2019-04-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20190430_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='position',
            field=models.DecimalField(decimal_places=5, max_digits=5, unique=True),
        ),
    ]
