# Generated by Django 2.2 on 2019-04-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20190430_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='position',
            field=models.DecimalField(decimal_places=5, max_digits=10, unique=True),
        ),
    ]
