# Generated by Django 2.2 on 2019-04-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20190430_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('is_archived', models.BooleanField(default=False)),
                ('position', models.DecimalField(decimal_places=5, max_digits=10, unique=True)),
                ('lst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.List')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
