# Generated by Django 2.2 on 2019-05-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
        migrations.RemoveField(
            model_name='list',
            name='position',
        ),
        migrations.AddField(
            model_name='list',
            name='cards_positions',
            field=models.TextField(null=True),
        ),
    ]
