# Generated by Django 2.2 on 2019-05-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20190502_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='lists_positions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='cards_positions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
